language: generic

sudo: required # Telling we are super user

services:
  - docker # telling to install docker

before_install:
  - docker build -t arvind/react_docker_deploy -f Dockerfile.dev .

script:
  - docker run -e CI=true arvind/react_docker_deploy npm run test # -e CI= true is for stopping the process when the test ran since test wait for our input and never ends

deploy:
  provider: elasticbeanstalk # AWS SERVICE
  region: ap-south-1
  app: docker-react
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-167546543537" # AWS s3
  bucket_path: "docker-react"
  on:
    branch: main # only deploy when merged or pushed to master branch
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
