language: generic

sudo: required # Telling we are super user

services:
  - docker # telling to install docker

before_install:
  - docker build -t arvind/react_docker_deploy -f Dockerfile.dev .

script:
  - docker run -e CI=true arvind/react_docker_deploy npm run test # -e CI= true is for stopping the process when the test ran since test wait for our input and never ends
